### PR TITLE
Remove explicit usage of self in project.

### PR DESCRIPTION
**Pull request by roberthein**
Changed `self insert` to `self remove` in our swift formatting rules.

### CODE REVIEW

**Comment by Elland** [comment]
That's the default. You can just remove the argument. 😉

**Comment by roberthein** [comment]
It's probably best to wait with merging this pr until other big pr's are merged.

**Comment by faymontage** [comment]
Yep we'll apply it and include the changes in this PR

**Comment by roberthein** [comment]
@yuliaveres Thanks! I will.

**Pull request merged**
